export const projectDetails = [
  {
    id: 1,
    projectName: "Verico website",
    projectImage: "/images/verico.jpg",
    dataAos: "fade-up",
    buttonText: "View live",
    buttonTextTwo: "Private",
    buttonLink: "https://getverico.com",
  },
  {
    id: 2,
    projectName: "Online Dictionary ",
    projectImage: "/images/dictionary.jpeg",
    dataAos: "fade-right",
    buttonText: "View live",
    buttonTextTwo: "View code",
    buttonLink: "https://online-dictionary.netlify.app/",
    buttonLinkTwo: "https://github.com/mbk97/online-dictionary",
  },

  {
    id: 3,
    projectName: "Crypto-cap Landing Page",
    projectImage: "/images/cryptocap.jpeg",
    dataAos: "fade-left",
    buttonText: "View live",
    buttonTextTwo: "View code",
    buttonLink: "https://mbk-crypto-application.netlify.app/",
    buttonLinkTwo: "https://github.com/mbk97/crypto",
  },
  {
    id: 4,
    projectName: "weather app",
    projectImage: "/images/weather.jpeg",
    dataAos: "fade-right",
    buttonText: "View live",
    buttonTextTwo: "View code",
    buttonLink: "https://mbk-weather-app.netlify.app/",
    buttonLinkTwo: "https://github.com/mbk97/weather-app",
  },

  {
    id: 5,
    projectName: "Cryptoverse Dashboard",
    projectImage: "/images/cryptoverse.jpeg",
    dataAos: "fade-up",
    buttonText: "View live",
    buttonTextTwo: "View code",
    buttonLink: "https://mbk-crypto-app.netlify.app/",
    buttonLinkTwo: "https://github.com/mbk97/cryptoverse",
  },
  {
    id: 6,
    projectName: "Movie Application",
    projectImage: "/images/movie.jpeg",
    dataAos: "fade-left",
    buttonText: "View live",
    buttonTextTwo: "View code",
    buttonLink: "https://redux-movie.netlify.app/",
    buttonLinkTwo: "https://github.com/mbk97/redux-movie",
  },
];
